### ISSUE TITLE
"square" icon not useful

### ISSUE THREAD

**Issue by jhit** [icons8/line-awesome#5]
Can you please replace the square icon in LineAwsome with the "square outline" icon from the icons8 / Windows 10 set. The current square icon is absolutely incompatible with "check-square" and "plus-square" and breaks a lot of stuff when used as FontAwesome replacement. For example check-lists.

**Comment by fatawesome** [comment]
Hello! Recently we've released the new version of Line Awesome. Check if this icon works for you now 😊

**Comment by YoungElPaso** [comment]
This still isn't really resolved. None of the squares really match up directly to the check-square for isntance.  The .lar square is still slightly smaller and the stop icon is also not quite right.  I'm in the exact situation as @jhit - making a checklist - and the only thing I can do is slightly bump up the size of the square icon using a different font-size, which to be honest, is a hack.
